### PR TITLE
feat: add scss and folder architecture [MP-93]

### PR DESCRIPTION
**Pull request by adrianHards**
added basic folder structure, potential conflict with tailwind, with bootstrap we would import external library into application.scss, but don't see a way to do that with Tailwind ...

### CODE REVIEW

**Review by FlipBernardo — COMMENTED** [review]
looks good, I was sidestepping with Adrian on this, and the scss is definitely connected. Just the small doubt on how is it actually going to work with Tailwind. We would have to keep an eye on that for the future, I guess.
I'll let @diandrae have a look before merging tho.

**Comment by adrianHards** [comment]
Not quite sure what changed for these tests to fail, I haven't touched them. Is this from another PR?

25 examples, 3 failures

Failed examples:

rspec ./spec/requests/pathway_spec.rb:8 # Pathways GET /edit mentor can access should return 200:OK
rspec ./spec/system/users_spec.rb:12 # Users sign in valid with correct credentials
rspec ./spec/system/users_spec.rb:25 # Users Sign up valid with correct credentials

**Comment by CraigDoesCode** [comment]
Screenshot 2022-11-17 at 01 00 50
I think the scss might be the cause of som of the errors

**Comment by CraigDoesCode** [comment]
Lets pause work on this, until we get requirements on design from diandra too

**Comment by adrianHards** [comment]
> Screenshot 2022-11-17 at 01 00 50
> 
> I think the scss might be the cause of som of the errors

nice catch, this is likely related to two conflicting stylesheet forms.

**Pull request closed without merging**
