### PR TITLE
fix: clobber assets

### PR DESCRIPTION
**Pull request by adrianHards**
Quick fix. Originally I needed to stop the server and precompile every time I updated the css, rather than simply refresh the browser to see css updates. So, to fix that I made a few changes. 

After merge, you should:

1. npm install
2. yarn install
3. bin/rails assets:clobber
4. bin/dev

I'll make a video demo'ing this all later. CSS should no update on page refresh, though it's a little slower than when it was just Tailwind.

### CODE REVIEW

**Comment by adrianHards** [comment]
All the Tailwind changes were the result of my extension auto-arranging classes when I viewed the file. I didn't make any styling changes.

**Comment by BsBou** [comment]
After following all the steps, including cobbler, I get this rails error when running bin/dev
`The asset "tailwind.css" is not present in the asset pipeline.`

Running rails assets:precompile fixed it, and allows me to run the server, but as you said, to server needs to be restarted in order to update CSS
I fixed it by deleting the `../public/assets` folder. I'm now able to run Tailwind and update CSS without needing to restart

**Comment by BsBou** [comment]
nevermind, just pulled latest commit with changes to procfile and it works as expected.

**Comment by BsBou** [comment]
> > After following all the steps, including cobbler, I get this rails error when running bin/dev `The asset "tailwind.css" is not present in the asset pipeline.`
> > Running rails assets:precompile fixed it, and allows me to run the server, but as you said, to server needs to be restarted in order to update CSS I fixed it by deleting the `../public/assets` folder. I'm now able to run Tailwind and update CSS without needing to restart
> 
> would you mind pulling latest @BsBou and trying again, I forgot to add something to procfile that generates the tailwind.css file (didn't need to delete public folder though, so that's interesting). Can clobber and then run bin/dev to confirm it works.

assets folder in public folder is a minified build that gets created when we run assets:precompile 
It's sort of a static snapshot taken when we precompile (what happens in production, or we can do it in development by running assets:precompile)
deleting the assets folder reverts it to the default state of listening to any changes. 
I'm sure there's a more elegant way of doing it.

**Review by BsBou — APPROVED** [review]

**Comment by adrianHards** [comment]
> > > After following all the steps, including cobbler, I get this rails error when running bin/dev `The asset "tailwind.css" is not present in the asset pipeline.`
> > > Running rails assets:precompile fixed it, and allows me to run the server, but as you said, to server needs to be restarted in order to update CSS I fixed it by deleting the `../public/assets` folder. I'm now able to run Tailwind and update CSS without needing to restart
> > 
> > 
> > would you mind pulling latest @BsBou and trying again, I forgot to add something to procfile that generates the tailwind.css file (didn't need to delete public folder though, so that's interesting). Can clobber and then run bin/dev to confirm it works.
> 
> assets folder in public folder is a minified build that gets created when we run assets:precompile It's sort of a static snapshot taken when we precompile (what happens in production, or we can do it in development by running assets:precompile) deleting the assets folder reverts it to the default state of listening to any changes. I'm sure there's a more elegant way of doing it.

Yep, the solution/problem had nothing to do with precompile and clobber really 😅 but clobber at least confirmed that the necessary files are generated by the postcss script. And then I had to change a few things to get sass to update on save.

**Pull request merged**
