### PR TITLE
fix: update .ruby-version and gemfile to use ruby 3.1.2 [MP-71]

### PR DESCRIPTION
**Pull request by adrianHards**
- this update will allow us to simply run `bin/dev` in our terminals rather than yarn build watch and rails s etc.
- you will likely need to run bundle install after pulling

PR notes:

I had to update the tests.yml to accept the updated version of Ruby. First, I updated the version to 3.1.2 but was still having issues. I then updated `uses: ruby/setup-ruby` to what is considered the preferred value (see commit) and omitted specifying which version of Ruby to run (it looks in the .ruby-version file instead), and now the tests pass. 

-  omitted ruby version as not needed where there's a ruby-version file (see: https://github.com/ruby/setup-ruby)
- more info on testing: https://docs.github.com/en/enterprise-server@3.4/actions/automating-builds-and-tests/building-and-testing-ruby

### CODE REVIEW

**Comment by adrianHards** [comment]
Ruby 3.1.2 too bleeding edge apparently: https://github.com/actions/runner-images/issues/6399

I'll see what I can do in the mean time

**Comment by CraigDoesCode** [comment]
you should be able to run bin/dev already. that how i run the server

**Comment by adrianHards** [comment]
> you should be able to run bin/dev already. that how i run the server

odd, when I tried it said it wasn't available with the current version of Ruby. A good lesson in how to upgrade a project's Ruby version if not. Up to you if you want to do so, probably no harm? Some of the changes I made are recommended regardless (like using @v1 which is apparently better able to accept further version changes should they be required).

**Review by CraigDoesCode — APPROVED** [review]
lets do it

**Pull request merged**
